export const optionsCurrency = [
    { value: 'USD', label: 'Dolar Americano' },
    { value: 'EUR', label: 'Euro' },
    { value: 'GBP', label: 'Libra Esterlina' },
    { value: 'JPY', label: 'Yen Japones' },
    { value: 'CNY', label: 'Yuan Chino' },
    { value: 'KRW', label: 'Won Surcoreano' },
    { value: 'ARS', label: 'Peso Argentino' },
    { value: 'MXN', label: 'Peso Mexicano' },
    { value: 'COP', label: 'Peso Colombiano' },
    { value: 'BRL', label: 'Real Brasilero' },
    { value: 'CLP', label: 'Peso Chileno' },
    { value: 'VEF', label: 'Bolivar Venezolano' },
    { value: 'PEN', label: 'Sol Peruano' },
    { value: 'UYU', label: 'Peso Uruguayo' },
    { value: 'PYG', label: 'Guarani Paraguayo' },
    { value: 'BOB', label: 'Boliviano' },
]
